### ISSUE TITLE
Need Visitor Counter!

### ISSUE THREAD

**Issue by AliakseiKorneu** [andrewnester/fulllungs#10]
![Count](http://ktonanovenkogo.ru/image/schetchiki-poseschenii.jpg)

ASAP!

**Comment by andrewnester** [comment]
@AliakseiKorneu great! some suggestion what counter to use?

**Comment by AliakseiKorneu** [comment]
@andrewnester I think, some of these counters will be looked really good on our site. Check them out:

![petushki](http://www.freecounterstat.com/cache_image/438.png)
![drugs](http://www.freecounterstat.com/cache_image/686.png)
![animals](http://www.freecounterstat.com/cache_image/957.png)

By the way, I've found them [here](http://www.freecounterstat.com/). These guys are really cool, you can even get some code which you can paste directly to the page! Awesome!

**Comment by AliakseiKorneu** [comment]
Guys! Obviously, this issue is stuck, can we finally get any solution?

**Comment by andrewnester** [comment]
@AliakseiKorneu could you please send CR implementing this?

**Comment by andrewnester** [comment]
@AliakseiKorneu almost an year passed, any progress?

**Comment by AliakseiKorneu** [comment]
@andrewnester It's very sad to disappoint you, but there is no any progress :( The task proved to be much more complex and complicated than I expected. I think we need some skillful expert's help here.

@IharKrasnik, could you please help us with this issue? Thanks in advance!

**Comment by AliakseiKorneu** [comment]
Guys! Any updates here?

**Comment by AliakseiKorneu** [comment]
Guys, c'mon! Let's get it done! Any help will be appreciated.

**Comment by AliakseiKorneu** [comment]
Almost 3 years but we did it!
