### ISSUE TITLE
Add currency chart, please! 

### ISSUE THREAD

**Issue by AliakseiKorneu** [andrewnester/fulllungs#16]
It would be very convenient to have currency chart on this site!

**Comment by andrewnester** [comment]
@AliakseiKorneu thanks for your interest! Feel free to send PR ;)

**Comment by AliakseiKorneu** [comment]
@andrewnester Hi! I've just added a pull request: https://github.com/andrewnester/fulllungs/pull/17

**Comment by andrewnester** [comment]
Thanks!
