### ISSUE TITLE
I need scroll to top button, ASAP

### ISSUE THREAD

**Issue by IharKrasnik** [andrewnester/fulllungs#2]
Why do I need to scroll up to the top using my mouse? No programatic support, srsly?
My wheel is almost broken, it's unacceptable!

**Comment by andrewnester** [comment]
@IharKrasnik feel free to send PR adding this :)

**Comment by andrewnester** [comment]
Finally, with a help of @harsh2102 we closed it after more than 2 years! 🥇 🍾 🎉

**Comment by harsh2102** [comment]
thank you for approving.its my pleasure
