### ISSUE TITLE
Configure SSL on fulllungs.club 

### ISSUE THREAD

**Issue by AliakseiKorneu** [andrewnester/fulllungs#24]
It would be great to configure SSL on our great site cause security is a very important thing nowadays. When I open the site I see these, it's disgusting. 

![](https://i.imgur.com/5EV5iaq.png)

**Comment by IharKrasnik** [comment]
@AliakseiKorneu  What is SSL?
Is it some drug?

**Comment by andrewnester** [comment]
@IharKrasnik https://www.digicert.com/ssl/

Thanks @AliakseiKorneu for raising awareness regarding website security, implemented!

<img width="329" alt="Screenshot 2019-10-15 at 20 59 32" src="https://user-images.githubusercontent.com/2969996/66861228-ec474900-ef8e-11e9-8bcd-602104e93992.png">
