### ISSUE TITLE
Add links to new live videos

### ISSUE THREAD

**Issue by AliakseiKorneu** [andrewnester/fulllungs#25]
Hey! As you may see we've played a live show recently and you can find some footages on youtube. I think, it worth to add some new videos. E.g. you may use this links:

https://youtu.be/whrQ26ZIlcI
https://youtu.be/t1D5WEXMX3M

**Comment by kovsk1** [comment]
I'l do it

**Comment by andrewnester** [comment]
thanks for implementing this!
