### ISSUE TITLE
Support chat needed

### ISSUE THREAD

**Issue by lerakuntsevich** [andrewnester/fulllungs#29]
## Need help!

I think it is very good idea to add a support chat to your website! It will be very helpful because:

- [ ] I have some questions
- [ ] I need answers very soon

![2020-04-22 00 24 07](https://user-images.githubusercontent.com/46923485/79915434-9c5ea880-842f-11ea-98b6-945e039da34b.jpg)

**Comment by andrewnester** [comment]
thanks for reporting! it's already there, closing the ticket.

![Screenshot 2020-04-21 at 23 33 33](https://user-images.githubusercontent.com/2969996/79916210-9dd8a280-8428-11ea-9b04-63d8cf31a42a.png)
![Screenshot 2020-04-21 at 23 33 37](https://user-images.githubusercontent.com/2969996/79916225-a4ffb080-8428-11ea-93af-8ba40a50da61.png)
