### ISSUE TITLE
Why the site doesn't have any sound features?

### ISSUE THREAD

**Issue by AliakseiKorneu** [andrewnester/fulllungs#6]
It would be nice to add some sounds, music, noises to web page!

**Comment by andrewnester** [comment]
@AliakseiKorneu nice idea, I would suggest some reggaeton  playing in the background

**Comment by AliakseiKorneu** [comment]
@andrewnester can I implement a feature: when you hover Ihar Krasnik's photo with you cursor the sound of Ihar's «leu rychit» recording will be played?

**Comment by andrewnester** [comment]
@AliakseiKorneu I definitely respect all features related to Igor Krasnik! Feel free to send pull request

**Comment by AliakseiKorneu** [comment]
Please, see #9

**Comment by andrewnester** [comment]
Closed by #9
